weights: ./work_dir/recognition/kinetics_skeleton/Divide_ST_GCN/epoch50_model.pt

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'
    
# training
device: [3]