work_dir: ./work_dir/recognition/kinetics_skeleton_trim/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150 
  data_path: ./data/Trim/kinetics-skeleton/train_data.npy
  label_path: ./data/Trim/kinetics-skeleton/train_label.pkl
test_feeder_args:
  data_path: ./data/Trim/kinetics-skeleton/val_data.npy
  label_path: ./data/Trim/kinetics-skeleton/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 5
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0,1]
batch_size: 8
test_batch_size: 8

#optim
base_lr: 0.01
step: [20, 30, 40, 50]
num_epoch: 50



